#!/bin/sh
# The first script to run when handling a push from a client is pre-receive.
# It takes a list of references that are being pushed from stdin;
# if it exits non-zero, none of them are accepted.
# You can use this hook to do things like make sure none of the updated references are non-fast-forwards,
# or to do access control for all the refs and files they’re modifying with the push.

while read old new ref; do
	echo "Checking $ref $old->$new"
done >&2

# https://gist.github.com/caniszczyk/1327469


