#!/bin/sh

. ./gitserv

# Prepare .ssh folder and files
mkdir -p $HOME/.ssh
chmod 700 $HOME/.ssh
touch $HOME/.ssh/authorized_keys
chmod 600 $HOME/.ssh/authorized_keys

mkdir -p "$ROOT"

test -w "$KEYS" || die "File '$KEYS' is not writable"

# sudo chsh -s /usr/bin/git-shell gituser

ver() {
	git describe --long --dirty 2>/dev/null > VERSION || \
		echo "Initial version-g$(git rev-parse --short HEAD)"
}


case $1 in
print)
	printf "PWD: %s\n" "$PWD"
	printf "ROOT: %s\n" "$ROOT"
	printf "LOGS: %s\n" "$LOGS"
	printf "KEYS: %s\n" "$KEYS"
	cat $ROOT/users.conf
	;;
update)
	printf "Old version: %s\n" "$(ver)"
	git pull
	test -n "$3" && git reset --hard "$3"
	printf "New version: %s\n" "$(ver)"
	;;
reset)
	printf "" > $FILE
	;;
esac



