#!/bin/sh
#-
#- EXAMPLES
#-
#-    git> user add john
#-    git> user conf john group admin
#-    git> user conf john name "John Smith"
#-    git> user addkey john
#-    git> user rmkey john fingerprint
#-    git> user find
#-    git> user find john
#-    git> user show john
#-    git> user drop john
#-


USER_RE='[a-z][-a-z0-9]\{1,16\}[a-z0-9]$'
LINE='command="env USER=%s GROUP=%s %s",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty %s\n'

. ./gitserv

is_admin

user_exists() {
	expr "$1" : "$USER_RE" >/dev/null 2>&1
	test "$?" = "0" || die "Name '$1' is not available" "It should match to ^$USER_RE"
	test -n "$(user_conf "user.$1.created")"
	test "$?" = "${2:-0}" || die "${3:-"User '$1' does not exists"}"
}

case $1 in
add)
	user_exists "$2" 1 "Name '$2' is not available"
	user_conf "user.$2.created" "$TIME"
	user_conf "user.$2.group" "all"
	printf "User '%s' added\n" "$2"
	;;
drop)
	user_exists "$2"
	if ask "Drop user '$2'?" "N/y"; then
		user_conf --get-regexp "^user\.$2\." >> "$TIME.$2.conf"
		user_conf --remove-section "user.$2"
		sed -ie "/ USER=$2 /d" $KEYS
		printf "User '%s' dropped\n" "$2"
	fi
	;;
addkey)
	user_exists "$2"
	printf "Input the key (ssh-rsa AAAAB3Nza...): "
	read KEY
	TMP=$(mktemp -u)
	printf %s "$KEY" > $TMP
	ssh-keygen -lf $TMP > $TMP.fp 2>/dev/null || die "Invalid key"
	read len FP note <$TMP.fp
	rm $TMP $TMP.fp

	test -n "$(user_conf "key.$FP.created")" && die "Key exists"

	user_conf "key.$FP.created" "$TIME"
	user_conf "key.$FP.owner" "$2"
	user_conf "key.$FP.note" "${note#/tmp/* }"

	printf "$LINE" "$2" "$HOME/gitserv" "$KEY" >> $KEYS
	printf "Key '%s' added for '%s'\n" "$FP" "$2"
	;;
rmkey)
	test -n "$(user_conf "key.$2.created")" || die "Key not exists"
	user_conf --remove-section "key.$2"
	;;
conf)
	user_exists "$2"
	user_conf ${4:+"--replace-all"} "user.$2.$3" ${4:+"$4"}
	;;
group)
	user_exists "$2"
	user_conf ${4:+"--replace-all"} "user.$2.$3" ${4:+"$4"}
	;;
show)
	user_exists "$2"
	user_conf --get-regexp "^user\.$2\."
	;;
find)
	printf "LIST OF USERS:${2:+" (filter: ${2:-*})"}\n"
	user_conf --get-regexp "^user\.$2.*\.created$" | column
	;;
*)
	doc user;;
esac


